In [6]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
import pandas as pd
from sklearn.metrics import r2_score
import pickle

In [7]:
csv_file_path = 'C:\\Users\\hp\\OneDrive\\Desktop\\assM\\cleaned_data.csv'

In [8]:
df = pd.read_csv(csv_file_path, encoding='utf-8')
df.iloc[:4]

,Year,Price,Number of Passengers,Engine Power,Alarm,CD Player,Air Conditioning,Leather Seats,Airbags,Sunroof,...,هونداي سانتافيه,هونداي سنتافيه,هونداي سوناتا,هونداي فيرنا,هونداي فيلوستر,هونداي فينيو,هونداي كليك,هونداي كوبيه,هونداي كونا,هونداي ٢٠٠٦
0,2014,0.682516,5,0.625000,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2007,0.406442,8,0.833333,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,1982,0.030292,5,0.169167,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2015,0.440951,5,0.375000,1,1,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
X = df.drop(columns=['Price'])
y = df['Price']
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [5]:
# Create polynomial features
poly_features = PolynomialFeatures(degree=2)
X_train_poly = poly_features.fit_transform(X_train)
X_test_poly = poly_features.transform(X_test)

# Fit the polynomial regression model
poly_reg = LinearRegression()
poly_reg.fit(X_train_poly, y_train)

# Predict on the test set
y_pred_poly = poly_reg.predict(X_test_poly)

# Calculate MSE and MAPE
mse_poly = mean_squared_error(y_test, y_pred_poly)
mape_poly = mean_absolute_percentage_error(y_test, y_pred_poly)
r2_lr = r2_score(y_test, y_pred_poly)

print("Polynomial Regression:")
print("MSE:", mse_poly)
print("MAPE:", mape_poly)
print("R2 score for Polynomial Regression model:", r2_lr)

In [ ]:
# Fit the kNN model
knn_reg = KNeighborsRegressor(n_neighbors=5)
knn_reg.fit(X_train, y_train)

# Predict on the test set
y_pred_knn = knn_reg.predict(X_test)

# Calculate MSE and MAPE
mse_knn = mean_squared_error(y_test, y_pred_knn)
mape_knn = mean_absolute_percentage_error(y_test, y_pred_knn)
r2_knn = r2_score(y_test, y_pred_knn)
print("kNN:")
print("MSE:", mse_knn)
print("MAPE:", mape_knn)
print("R2 score for kNN model:", r2_knn)

kNN:
MSE: 0.0011628146066150519
MAPE: 0.8407343038555453
R2 score for kNN model: 0.5954510414546303

In [10]:
# Fit the Decision Tree model
dt_reg = DecisionTreeRegressor()
dt_reg.fit(X_train, y_train)

# Predict on the test set
y_pred_dt = dt_reg.predict(X_test)

# Calculate MSE and MAPE
mse_dt = mean_squared_error(y_test, y_pred_dt)
mape_dt = mean_absolute_percentage_error(y_test, y_pred_dt)
r2_dt = r2_score(y_test, y_pred_dt)

print("Decision Tree:")
print("MSE:", mse_dt)
print("MAPE:", mape_dt)
print("R2 score for Decision Tree model:", r2_dt)

Decision Tree:
MSE: 0.014114733962288666
MAPE: 0.3494844287894787
R2 score for Decision Tree model: 0.6872182840551743

In [12]:
# Save the model object into a file using pickle
with open('decision_tree_model.pkl', 'wb') as file:
    pickle.dump(dt_reg, file)